

# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
      timezone: "Europe/London"
    groups:
      # Bundle updates in the pyproject.toml [tool.poetry.dependencies] section
      production-dependencies:
        dependency-type: "production"
      # Should bundle updates in the pyproject.toml [tool.poetry.groups.*] sections
      # but leave the sphinx ecosystem alone
      development-dependencies:
        dependency-type: "development"
        exclude-patterns:
        - "sphinx*"
      sphinx: 
      # Separately allow it to move sphinx updates within minor versions
        applies-to: version-updates
        patterns:
        - "sphinx*"
        update-types:
        - "minor"
        - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
