[core]
[hydrology.depends]
init = ['plants']
update = ['plants', 'abiotic_simple']
[abiotic_simple]
[animal]
[litter.depends]
update = ['plants', 'hydrology', 'abiotic_simple']
[soil.depends]
init = ['hydrology', 'abiotic_simple']
update = ['litter', 'hydrology', 'abiotic_simple']
