[[variable]]
axis = []
description = "Air temperature profile"
unit = "C"
variable_type = ""

[[variable]]
axis = []
description = "Air temperature at reference height (2m)"
unit = "C"
variable_type = ""

[[variable]]
axis = []
description = "Shortwave light albedo"
unit = "-"
variable_type = ""

[[variable]]
axis = []
description = "Visible light albedo"
unit = "-"
variable_type = ""

[[variable]]
axis = []
description = "Animal respiration aggregated over all functional types"
initialised_by = "animal"
name = "animal_respiration"
unit = "ppm"
variable_type = ""

[[variable]]
axis = []
description = "Atmospheric CO2 concentration profile"
unit = "ppm"
variable_type = ""

[[variable]]
axis = []
description = "Atmospheric CO2 concentration at reference height (above canopy)"
unit = "ppm"
variable_type = ""

[[variable]]
axis = []
description = "Atmospheric pressure profile"
unit = "kPa"
variable_type = ""

[[variable]]
axis = []
description = "Atmospheric pressure at reference height (2m)"
unit = "kPa"
variable_type = ""

[[variable]]
axis = []
description = "Bulk aerodynamic resistance"
unit = "s m-1"
variable_type = ""

[[variable]]
axis = []
description = "Shortwave radiation absorbed by individual canopy layers"
unit = "J m-2"
variable_type = ""

[[variable]]
axis = []
description = "Canopy height"
unit = "m"
variable_type = ""

[[variable]]
axis = []
description = "Heights of canopy layers"
unit = "m"
variable_type = ""

[[variable]]
axis = []
description = "Canopy temperature of individual layers"
unit = "C"
variable_type = ""

[[variable]]
axis = []
description = "Elevation above sea level"
unit = "m"
variable_type = ""

[[variable]]
axis = []
description = "Evapotranspiration"
unit = "-"
variable_type = ""

[[variable]]
axis = []
description = "Friction velocity"
unit = "m s-1"
variable_type = ""

[[variable]]
axis = []
description = "Ground heat flux"
unit = "J m-2"
variable_type = ""

[[variable]]
axis = []
description = "Latent heat flux from canopy layers"
unit = "J m-2"
variable_type = ""

[[variable]]
axis = []
description = "Latent heat flux from surface layer"
unit = "J m-2"
variable_type = ""

[[variable]]
axis = []
description = "Leaf area index"
unit = "m m"
variable_type = ""

[[variable]]
axis = []
description = "Longwave radiation from individual canopy layers"
unit = "J m-2"
variable_type = ""

[[variable]]
axis = []
description = "Longwave radiation from surface layer"
unit = "J m-2"
variable_type = ""

[[variable]]
axis = []
description = "Mean annual temperature = temperature of deepest soil layer"
unit = "C"
variable_type = ""

[[variable]]
axis = []
description = "Temperature-dependent molar density of air"
unit = "kg m-3"
variable_type = ""

[[variable]]
axis = []
description = "Net shortwave radiation at the surface"
unit = "J m-2"
variable_type = ""

[[variable]]
axis = []
description = "Plant net CO2 assimilation"
unit = "ppm"
variable_type = ""

[[variable]]
axis = []
description = "Top of canopy photosynthetic photon flux density"
unit = "mol m-2"
variable_type = ""

[[variable]]
axis = []
description = "Precipitation"
unit = "mm"
variable_type = ""

[[variable]]
axis = []
description = "Precipitation that reaches surface"
name = "precipitation_surface"
unit = "mm"
variable_type = ""

[[variable]]
axis = []
description = "Relative humidity profile"
name = "relative_humidity"
unit = "%"
variable_type = ""

[[variable]]
axis = []
description = "Relative humidity at reference height (2m)"
name = "relative_humidity_ref"
unit = "%"
variable_type = ""

[[variable]]
axis = []
description = "River discharge"
name = "river_discharge"
unit = "m3 s-1"
variable_type = ""

[[variable]]
axis = []
description = "Estimated stream flow"
name = "stream_flow"
unit = "mm per time step"
variable_type = ""

[[variable]]
axis = []
description = "Roughness length for momentum"
name = "roughness_length_momentum"
unit = "m"
variable_type = ""

[[variable]]
axis = []
description = "Sensible heat flux from canopy and surface"
name = "sensible_heat_flux"
unit = "J m-2"
variable_type = ""

[[variable]]
axis = []
description = "Sensible heat flux from canopy"
name = "sensible_heat_flux_canopy"
unit = "J m-2"
variable_type = ""

[[variable]]
axis = []
description = "Sensible heat flux from surface layer"
name = "sensible_heat_flux_soil"
unit = "J m-2"
variable_type = ""

[[variable]]
axis = []
description = "Downward shortwave radiation"
name = "shortwave_in"
unit = "J m-2"
variable_type = ""

[[variable]]
axis = []
description = "Soil evaporation"
name = "soil_evaporation"
unit = "mm"
variable_type = ""

[[variable]]
axis = []
description = "Soil moisture as volumetric relative water content"
name = "soil_moisture"
unit = "-"
variable_type = ""

[[variable]]
axis = []
description = "Soil respiration"
name = "soil_respiration"
unit = "ppm"
variable_type = ""

[[variable]]
axis = []
description = "Soil temperature profile"
name = "soil_temperature"
unit = "C"
variable_type = ""

[[variable]]
axis = []
description = "Specific heat of air"
unit = "kJ kg-1"
variable_type = ""

[[variable]]
axis = []
description = "Specific humidity of air"
unit = "g kg-1"
variable_type = ""

[[variable]]
axis = []
description = "Subsurface runoff"
unit = "mm"
variable_type = ""

[[variable]]
axis = []
description = "Fraction of sunshine hours, between 0 and 1"
unit = "-"
variable_type = ""

[[variable]]
axis = []
description = "Surface runoff generated in each grid cell"
unit = "mm"
variable_type = ""

[[variable]]
axis = []
description = "Accumlated surface runoff"
unit = "mm"
variable_type = ""

[[variable]]
axis = []
description = "Searchable surface water"
unit = "%"
variable_type = ""

[[variable]]
axis = []
description = "Top of canopy downward shortwave radiation"
unit = "J m-2"
variable_type = ""

[[variable]]
axis = []
description = "Vertical flow of water through soil column"
unit = "mm per time step"
variable_type = ""

[[variable]]
axis = []
description = "Wind above canopy"
unit = "m s-1"
variable_type = ""

[[variable]]
axis = []
description = "Wind profile within and below canopy"
unit = "m s-1"
variable_type = ""

[[variable]]
axis = []
description = "Wind speed at reference height (10m)"
unit = "m s-1"
variable_type = ""

[[variable]]
axis = []
description = "Size of low molecular weight carbon pool"
unit = "kg C m-3"
variable_type = ""

[[variable]]
axis = []
description = "Size of mineral associated organic matter pool"
unit = "kg C m-3"
variable_type = ""

[[variable]]
axis = []
description = "Size of microbial biomass pool"
unit = "kg C m-3"
variable_type = ""

[[variable]]
axis = []
description = "Size of microbial biomass pool"
unit = "kg C m-3"
variable_type = ""

[[variable]]
axis = []
description = "Bulk density of soil"
unit = "kg m-3"
variable_type = ""

[[variable]]
axis = []
description = "Soil pH"
unit = "pH"
variable_type = ""

[[variable]]
axis = []
description = "Above ground metabolic litter pool"
unit = "kg C m^-2"
variable_type = ""

[[variable]]
axis = []
description = "Above ground structural litter pool"
unit = "kg C m^-2"
variable_type = ""

[[variable]]
axis = []
description = "Woody litter pool"
unit = "kg C m^-2"
variable_type = ""

[[variable]]
axis = []
description = "Below ground metabolic litter pool"
unit = "kg C m^-2"
variable_type = ""

[[variable]]
axis = []
description = "Below ground structural litter pool"
unit = "kg C m^-2"
variable_type = ""

[[variable]]
axis = []
description = "Rate of carbon addition to soil from litter"
initialised_by = "litter"
name = "litter_C_mineralisation_rate"
unit = "kg C m^-3 day^-1"
variable_type = ""

[[variable]]
axis = []
description = "Rate of excrement flow from animals into litter"
initialised_by = "animal"
name = "decomposed_excrement"
unit = "kg C m^-3 day^-1"
variable_type = ""

[[variable]]
axis = []
description = "Rate of decomposed carcass biomass flow from animals into litter"
initialised_by = "animal"
name = "decomposed_carcasses"
unit = "kg C m^-3 day^-1"
variable_type = ""

# BELOW TO BE CHECKED

[[variable]]
axis = []
description = "Lignin content of above ground structural litter"
name = "lignin_above_structural"
unit = ""
variable_type = ""

[[variable]]
axis = []
description = "Lignin content of above ground structural litter"
name = "lignin_below_structural"
unit = ""
variable_type = ""

[[variable]]
axis = []
description = "Lignin content of woody litter"
name = "lignin_woody"
unit = ""
variable_type = ""

[[variable]]
axis = []
description = "Cell ID of plant cohorts"
name = "plant_cohorts_cell_id"
unit = ""
variable_type = ""

[[variable]]
axis = []
description = "Plant functional type of plant cohorts"
name = "plant_cohorts_pft"
unit = ""
variable_type = ""

[[variable]]
axis = []
description = "Number of plant cohorts"
name = "plant_cohorts_n"
unit = ""
variable_type = ""

[[variable]]
axis = []
description = "Diameter at breast height of plant cohorts"
name = "plant_cohorts_dbh"
unit = ""
variable_type = ""

[[variable]]
axis = []
description = "Photosynthetic photon flux density"
name = "photosynthetic_photon_flux_density"
unit = ""
variable_type = ""

[[variable]]
axis = []
description = "Fraction of clay in soil"
name = "clay_fraction"
unit = ""
variable_type = ""

[[variable]]
axis = []
description = "Vapour pressure"
name = "vapour_pressure"
unit = ""
variable_type = ""

[[variable]]
axis = []
description = "Vapour pressure deficit"
name = "vapour_pressure_deficit"
unit = ""
variable_type = ""

[[variable]]
axis = []
description = "Air heat conductivity"
name = "air_heat_conductivity"
unit = ""
variable_type = ""

[[variable]]
axis = []
description = "Conductivity from reference height"
name = "conductivity_from_ref_height"
unit = ""
variable_type = ""

[[variable]]
axis = []
description = "Leaf air heat conductivity"
name = "leaf_air_heat_conductivity"
unit = ""
variable_type = ""

[[variable]]
axis = []
description = "Leaf vapour conductivity"
name = "leaf_vapour_conductivity"
unit = ""
variable_type = ""

[[variable]]
axis = []
description = "Latent heat of vapourisation"
name = "latent_heat_vapourisation"
unit = ""
variable_type = ""

[[variable]]
axis = []
description = "Aerodynamic resistance at surface"
name = "aerodynamic_resistance_surface"
unit = ""
variable_type = ""

[[variable]]
axis = []
description = "Accumulated subsurface flow"
name = "subsurface_flow_accumulated"
unit = ""
variable_type = ""

[[variable]]
axis = []
description = "Matric potential"
name = "matric_potential"
unit = ""
variable_type = ""

[[variable]]
axis = []
description = "Groundwater Storage"
name = "groundwater_storage"
unit = ""
variable_type = ""

[[variable]]
axis = []
description = "River discharge rate"
name = "river_discharge_rate"
unit = ""
variable_type = ""

[[variable]]
axis = []
description = "Total river discharge"
name = "total_river_discharge"
unit = ""
variable_type = ""

[[variable]]
axis = []
description = "Surface flow"
name = "subsurface_flow"
unit = ""
variable_type = ""

[[variable]]
axis = []
description = "Base flow"
name = "baseflow"
unit = ""
variable_type = ""

[[variable]]
axis = []
description = "layer_fapar"
name = "layer_fapar"
unit = ""
variable_type = ""

[[variable]]
axis = []
description = "layer_leaf_mass"
name = "layer_leaf_mass"
unit = ""
variable_type = ""

[[variable]]
axis = []
description = "layer_absorbed_irradiation"
name = "layer_absorbed_irradiation"
unit = ""
variable_type = ""

[[variable]]
axis = []
description = "soil_enzyme_pom"
name = "soil_enzyme_pom"
unit = ""
variable_type = ""

[[variable]]
axis = []
description = "soil_enzyme_maom"
name = "soil_enzyme_maom"
unit = ""
variable_type = ""
