[core]
[hydrology.depends]
init = ['plants']
update = ['plants', 'abiotic_simple']
[abiotic_simple]
[animals]
[litter.depends]
update = ['hydrology', 'abiotic_simple']
[soil.depends]
init = ['hydrology', 'abiotic_simple']
update = ['hydrology', 'abiotic_simple']
