name: Run integration

# When does this run?
# * when called by another workflow, such as the publishing actions, or
# * when manually triggered to check the integration tests on a branch.
on:
  workflow_call:
  workflow_dispatch:

jobs:
  # Run the CI checks to check it all runs normally and to define the test matrix
  ci_checks:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
  
  # Then if the standard CI checks pass run the integration tests
  integration_tests:
    needs: ci_checks
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # All supported OSs, minimum and maximum python version
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: ["3.12", "3.14"]
    
    steps:
    - uses: actions/checkout@v7

    - uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      run: |
        pipx install poetry --python python${{ matrix.python-version }}
        poetry --version

    - name: Install dependencies
      run: poetry install

    - name: Run integration tests
      run: poetry run pytest -m "integration"

    - name: Archive log for error checking on failure
      if: failure()
      uses: actions/upload-artifact@v7
      with:
        name: failed_tests_ve_run_cli_log
        path: ${{ runner.temp }}/log_file.log
        archive: false
        retention-days: 1
